---
logs:
  json: false
metrics:
  endpoint: 127.0.0.1:8001
source:
  tokio:
    worker_threads: 2
    affinity: 0-1
  rpc:
    url: http://127.0.0.1:8899/
    timeout: 30s
    concurrency: 10
  stream:
    source: richat # valid: richat, dragons_mouth
    endpoint: http://127.0.0.1:10000
    ca_certificate: null
    connect_timeout: null
    buffer_size: null
    http2_adaptive_window: null
    http2_keep_alive_interval: null
    initial_connection_window_size: null
    initial_stream_window_size: null
    keep_alive_timeout: null
    keep_alive_while_idle: false
    tcp_keepalive: 15s
    tcp_nodelay: true
    timeout: null
    max_decoding_message_size: 16_777_216 # 16MiB
    compression:
      accept: ["gzip", "zstd"]
      send: ["gzip", "zstd"]
    x_token: null
storage:
  blocks:
    max: 1_000
    rpc_getblock_max_retries: 10
    rpc_getblock_backoff_init: 100ms
    rpc_getblock_max_concurrency: 15
    files:
      - id: 0
        path: ./db/storage0
        size: 8gb
  rocksdb:
    path: ./db/alpamayo/rocksdb
    index_slot_compression: none
    index_sfa_compression: none
    read_channel_size: 40 # default: number of CPUs on the system * 5
    read_workers: 8 # default: number of CPUs on the system
  write:
    affinity: 2
  read:
    threads: 2
    affinity: 3-4
    requests_concurrency: 256
rpc:
  endpoint: 127.0.0.1:9000
  tokio:
    worker_threads: 2
    affinity: 5-6
  body_limit: 50KiB
  request_timeout: 60s
  calls:
    - getBlock
    - getBlockHeight
    - getBlocks
    - getBlocksWithLimit
    - getBlockTime
    - getLatestBlockhash
    - getSignaturesForAddress
    - getSignatureStatuses
    - getSlot
    - getTransaction
    - getVersion
    - isBlockhashValid
  gsfa_limit: 1000
  gss_transaction_history: true
  request_channel_capacity: 4096
  upstream:
    endpoint: http://127.0.0.1:8899
    user_agent: alpamayo/v0.1.0
    version: HTTP/1.1
    retries_max: 3
    retries_backoff_init: 100ms
  workers:
    threads: 8 # default is number of CPUs
    affinity: 7-14 # no affinity by default
    channel_size: 4096
