---
# Example configuration showing multiple upstream JSON-RPC support
logs:
  json: false
metrics:
  endpoint: 127.0.0.1:8001
source:
  tokio:
    worker_threads: 2
    affinity: 0-1
  http:
    rpc: http://127.0.0.1:8899/
    httpget: http://127.0.0.1:9000/
    timeout: 30s
    concurrency: 10
  stream:
    source: richat
    reconnect:
      backoff_init: 100ms
      backoff_max: 1s
    endpoint: http://127.0.0.1:10000
    keep_alive_while_idle: false
    tcp_keepalive: 15s
    tcp_nodelay: true
    max_decoding_message_size: 16_777_216
storage:
  backfilling:
    sync_to: 338_669_763
  blocks:
    max: 1_000
    http_getblock_max_retries: 10
    http_getblock_backoff_init: 100ms
    files:
      - id: 0
        path: ./db/alpamayo/storage0
        size: 8gb
        new_blocks: true
  rocksdb:
    path: ./db/alpamayo/rocksdb
    index_slot_compression: none
    index_sfa_compression: none
    read_workers: 8
  write:
    affinity: 2
  read:
    threads: 1
    affinity: 3-4
    thread_max_async_requests: 1024
    thread_max_files_requests: 32
rpc:
  endpoint: 127.0.0.1:9000
  tokio:
    worker_threads: 2
    affinity: 5-6
  body_limit: 50KiB
  request_timeout: 60s
  calls_httpget:
    - getBlock
    - getTransaction
  calls_jsonrpc:
    - getBlock
    - getBlockHeight
    - getBlocks
    - getBlocksWithLimit
    - getBlockTime
    - getClusterNodes
    - getFirstAvailableBlock
    - getInflationReward
    - getLatestBlockhash
    - getLeaderSchedule
    - getRecentPrioritizationFees
    - getSignaturesForAddress
    - getSignatureStatuses
    - getSlot
    - getTransaction
    - getVersion
    - isBlockhashValid
  gsfa_limit: 1000
  gss_transaction_history: true
  grpf_percentile: true
  gcn_cache_ttl: 1s
  request_channel_capacity: 4096
  # fallback for httpget (unchanged)
  upstream_httpget:
    endpoint: http://127.0.0.1:8899
    user_agent: alpamayo/v0.1.0
    version: HTTP/1.1
    timeout: 30s
  # NEW: Multiple upstream JSON-RPC configuration
  upstream_jsonrpc_multiple:
    default: "main"  # Name of the default upstream
    endpoints:
      main:  # Default upstream for most requests
        endpoint: http://127.0.0.1:8899
        user_agent: alpamayo/v0.1.0
        version: HTTP/1.1
        timeout: 30s
      archive:  # Specialized upstream for historical data
        endpoint: http://archive.example.com:8899
        user_agent: alpamayo/v0.1.0
        version: HTTP/1.1
        timeout: 60s  # Longer timeout for archive requests
      fast:  # Fast upstream for real-time data
        endpoint: http://fast.example.com:8899
        user_agent: alpamayo/v0.1.0
        version: HTTP/2.0
        timeout: 10s  # Shorter timeout for fast responses
    method_routing:
      # Route historical data requests to archive server
      getBlock: "archive"
      getTransaction: "archive"
      # Route real-time requests to fast server
      getSlot: "fast"
      getBlockHeight: "fast"
      getLatestBlockhash: "fast"
      # All other methods will use the default "main" upstream
  workers:
    threads: 8
    affinity: 7-14
    channel_size: 4096